groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.ListGroups.as_view(), name='all'),
    url(r'^new/$', views.CreateGroup.as_view(), name='create'),
    # slugify the actual group name so that duplicates are not allowed
    url(r'^posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_view(), name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave'),
]

groups/models.py
from django.db import models

# remove any chars that are not alphanumeric
from django.utils.text import slugify

# for link embedding, use markdown inside of posts
import misaka

# imports the user model currently active in this project
from django.contrib.auth import get_user_model

# call things off of the current user's session
User = get_user_model()

from django import template
from django.urls import reverse

# use custom template tags
register = template.Library()


# Create your models here.
class Group(models.Model):
    # I don't want groups to have overlapping group names
    name = models.CharField(max_length=255, unique=True)
    # no mistakes calling a url code, and group slugs don't overlap each other
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    # in case we want an html version of the description
    description_html = models.TextField(editable=False, default='', blank=True)
    # pass in a User object through the GroupMember class
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # whatever the name is, you can put spaces in it
        # so it will replace and lowercase things
        self.slug = slugify(self.name)
        # allows us to put markdown in there
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    # we want to link this class to both the user and the groups they belong to

    # a GroupMember can have membership to a Group
    group = models.ForeignKey(Group, related_name='memberships', on_delete='CASCADE')
    # we will have a user from above - the current user that's logged in
    # they're going to have some groups that they are a member of
    user = models.ForeignKey(User, related_name='user_groups', on_delete='CASCADE')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
# import the CBVs
from django.views import generic
from . import models
from .models import Group, GroupMember

from django.shortcuts import get_object_or_404
from django.contrib import messages


# someone is logged in and wants to create their own group
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    # i want them to be able to edit these fields
    fields = ('name', 'description')
    # connect it to the actual model
    model = Group


# to display posts inside the group
class SingleGroup(generic.DetailView):
    model = Group


# a list of al the groups
class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        # redirect to the detail view of that particular group
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    #     add checks in case this person is already a member of this group
    def get(self, request, *args, **kwargs):
        # try to get the object or return a 404
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            # grab a GroupMember object and create it with the user = current user
            # and group = group which is the group we created above the try statement
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member!')
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        # redirect to the detail view of that particular group
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    # make sure they can't accidentally leave a group they are not a part of
    def get(self, request, *args, **kwargs):
        try:
            # try to get a membership assuming that the user is already in that group
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        #     the GroupMember was never a member of that group
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, "Sorry you are not in this group!")
        else:
            membership.delete()
            messages.success(self.request, "You have left the group!")
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            {#        before the group content #}
            {% block pregroup %}
            {% endblock %}
            {% block group_content %}
            {% endblock %}
            {#        after the group content #}
            {% block postgroup %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    {#    with class based views, the context dict holds all the model attributes #}
    {#    the context dict called group is the lower-cased singular version of the model Group #}

    <div class="container">
        <h1>{{ group.name }}</h1>
        <h2> Member Count: {{ group.members.count }}</h2>

        <div class="content">
            {% if user in group.members.all %}
                {#        we only want this if the user is already in the group #}

                <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning"><span
                        class="fa fa-times-circle-o"></span> Leave</a>
            {% else %}
                <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-warning"><span
                        class="fa fa-check-circle-o"></span> Join</a>
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block group_content %}

    <div class="col-md-8">
        {#    if the group currently has no posts #}

        {% if group.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>

        {% else %}

            {% for post in group.posts.all %}
                {#                similar to {% extends %} but insert it into the middle of the file #}

                {% include "posts/_post.html" %}
            {% endfor %}

        {% endif %}
    </div>
{% endblock %}

groups/templates/groups/group_form.html
<!-- if someone wants to create a group -->
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
    <h4>Create a New Group! </h4>
    {#    link to your create view #}
    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary btn-large">Create</button>
        {% endbuttons %}
    </form>


{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {#            if the user is logged in, say welcome back #}
            {#            else, say this is the groups page, select one #}
            {% if user.is_authenticated %}
                <h2>Welcome Back!
                    {#                links to their profile where they have their posts #}
                    <a href="{% url 'posts:for_user' username=user.username %}">
                        {#                if you click on this link, ti wil take you to a list of all your posts #}
                        @{{ user.username }}
                    </a>
                </h2>
            {% endif %}
            {#        for everyone though show the following #}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
        {#    add a button so they can create a new group #}
        {% if user.is_authenticated %}
            {#        creating a group is also available in the nav bar, this is separate #}
            <a href="{% url 'groups:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span>
                Create New Group!</a>
        {% endif %}
    </div>

{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {#        the object list is a list of the actual groups objects #}
            {#            display the group name, number of members, number of posts #}
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}"
                   class="list-group-item list-group-item-action flex-column align-items-start">
                    <h3 class="mb-1">{{ group.name }}</h3>
                    <p class="mb-1">{{ group.description_html|safe }}</p>
                    <div class="d-flex w-40 justify-content-between">
                        <small class="text-muted"><span class="badge badge-secondary">
					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
                        <small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
                        <span></span><span></span>
                    </div>
                </a>

            {% endfor %}
        </div>
    </div>

{% endblock %}