posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'^new/$', views.CreatePost.as_view(), name='create'),
    #     when you click on a user, you should see all their posts
    url(r'^by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

posts/models.py
from django.db import models

# when someone creates a post, you can have them sent back to another page
from django.urls import reverse

from django.conf import settings
import misaka

from groups.models import Group
from django.contrib.auth import get_user_model

# connects the current post to whoever is logged in as a user
User = get_user_model()


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete='CASCADE')
    # the time posted is auto-generated for you
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete='CASCADE')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                               'pk': self.pk})

    class Meta:
        # in descending order
        ordering = ['-created_at']
        # every message is uniquely linked to a user
        unique_together = ['user', 'message']

posts/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.views import generic
from django.http import Http404

from braces.views import SelectRelatedMixin
from . import models
from . import forms

from django.contrib.auth import get_user_model
from django.contrib import messages

# when someone is logged in, use this User as the current user and call things off of that
User = get_user_model()


# a list of posts belonging to a group
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    # basically the foreign keys for this post
    # the user and the group that this post belongs to
    select_related = ('user', 'group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    # check whether the username is exactly equal to the username of whoever is logged in right now
    def get_queryset(self):
        try:
            # set the user that belongs to this particular post to
            # whatever username is exactly equal to the username of the user you click on
            # you want to fetch the posts that are related to the user
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    # grab the post user and return the context dict off of that
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        # return the context for the person who posted
        return context


# when you select a particular post, there is a detailed view on it
class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields I want someone to be able to edit
    fields = ('message', 'group')
    model = models.Post

    # connect the post to the user itself
    # check whether the form is valid
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    # once you delete a post, what is the success url
    # takes you back to all the posts
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    # a lot of these come with the CBV, good documentation
    # return something saying the post was deleted
    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<!-- will inject this into other html files -->

<div class="media">
    {#this is essentially the link between clicking on someone's name and visiting their profile #}
    {# in this case, the profile is simply a list of their posts #}
    <h3 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>

    <div class="media-body">
{#        <strong>{{ post.user.username }}</strong>#}
        <h5>{{ post.message_html|safe }}</h5>
        {#        indicate what time this post was created at #}
        <time class="time"><a
                href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
        {% if post.group %}
            <span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
        {% endif %}


        <div class="media-footer">
            {% if user.is_authenticated and post.user == user and not hide_delete %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                    <span class="fa fa-remove text-danger" aria-hidden="true"></span>
                    <span class="text-danger icon-label">Delete</span>
                </a>
            {% endif %}
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post %}{% endblock %}
	</div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    <h3>Are you sure you want to delete this post?</h3>

    <div class="posts">
        {#includes the post you are going to delete#}
        {% include "posts/_post.html" with post=object hide_delete=True %}
    </div>

    {#    submits to our delete view#}
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
           class="btn btn-light btn-large">Cancel</a>
    </form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    {#    all the heavy lifting for the post detail was inside _post.html #}
    {% include "posts/_post.html" %}
{% endblock %}

posts/templates/posts/post_form.html
<!-- the html template linked to creating a new post -->
{% extends "posts/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
    <h4>Create New Post</h4>
    <form method="POST" action="{% url 'posts:create' %}" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary btn-large">Post</button>
        {% endbuttons %}
    </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
    <div class="col-md-4">
        {% if request.user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    {#                groups they belong to #}
                    <h5 class="title">Your Groups</h5>
                    <ul class="list-unstyled">
                        {#                    allows us to link from posts to the group member #}
                        {#            if a user is logged in, we want to list out thier groups #}
                        {#            in models.py inside groups, you had register = template.Library()#}
                        {#            that allowed us to use the related_name='user_groups' inside GroupMember #}
                        {% for member_group in get_user_groups %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card card-with-shadow">
            <div class="content">
                <h5 class="title">All groups</h5>
                <ul class="list-unstyled">
                    {# {% get_other_groups as other_groups %} #}
                    {% for other_group in get_other_groups %}
                        <li class="group li-with-bullet"><a
                                href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/user_post_list.html
<!-- if you click on a user you should see their post -->
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}